language: node_js
node_js:
  - "node"
  - "11.1.0"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn test
  - codecov
