language: node_js
node_js:
- 11.1.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
- export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
- yarn global add codecov
script:
- yarn test --coverage
- codecov
deploy:
  provider: heroku
  app:
    master: react-tictactoe-frontend
  api_key:
    master:
      secure: mtLrtn9YxxsaWSWm+mKwqDdebrYZXcHInP0TSRUCYQf+xTSeLi2jRyUWtoPMdqe/kU0hmpSxVGAQ1gAnuL/6MGzQNNf2FKrjfMcxUT+CX81R0KWHDp2SiWX4fVio0o1XUCNyYikrNhxYntQFBgOu70YHVo0yhrSH5igzjB4eXFg/C45Ilh1HWPrNnd9DS0j68U19N4kvyu/SPeYPzPgI8UNr4ISYIuPzzdCuDFqXxAjI3IMWkjSYkaTztDv7QfrtNrv0cZKudPmqU7SsDCKG4ZMF+fc1Aslk6TJ44DPztf9CU8lsHgz4JcBh77QOyHU3N7AyaEr06zdr34ys2rO3DeJ5ZPGxueJjvLD5YcJcolpmoGSf4GVZF2MXjh0TDHj9xufXP6w+gqUBMVmvog3wDqjTVBu1n5JFLwQ2yqWLHVcl0AYVxZYDPP4ZWDsc6if804JzI9oVfonhFmArj89AZPt0OnOjXazZ8/cGSryB0CNez+5IBuDn1UashXk6OTc95zpG/DK1eZS8UOtR8bWkavydNxocvWsQjKdFzEk7vJJ489TXj41lueR2Vq579ANl2sHTT8JHkGbpIGesZMckR+NJsgnVqKRSs/yOz4gxFr2AMMnz0LxfZclwbSGOPlY93bongM8Hz8HKTte2pQIcejkBECfBxbG2raeU48Q16PE=
